import json

# Process example2.ipynb
with open('example2.ipynb', 'r') as f:
    nb = json.load(f)

new_cells = []
for cell in nb['cells']:
    if cell['cell_type'] == 'markdown' and 'fbm3d' in cell['source'][0]:
        new_cells.append({
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "# fbm3d Example 2: Advanced ISM Density Field Generation\n",
                "\n",
                "This notebook demonstrates advanced usage of the `fbm3d_ISM` class:\n",
                "1. Generating density fields with non-cubic grid dimensions (e.g., $129 \\times 100 \\times 110$)\n",
                "2. Restricting fluctuations to specific scales using `kmin` and `kmax`\n",
                "3. Advanced analysis including power spectrum comparisons and scatter plots\n",
                "4. Saving density fields to FITS files\n",
                "5. Adjusting the spatial center of the generated fields using the `centering` option\n"
            ]
        })
    elif cell['cell_type'] == 'code':
        source = "".join(cell['source'])
        if "nx, ny, nz = 129, 100, 110" in source:
            new_cells.append({
                "cell_type": "markdown",
                "metadata": {},
                "source": [
                    "## 1. Generating a Non-Cubic Density Field\n",
                    "\n",
                    "Unlike Example 1, here we generate a 3D field with unequal dimensions (`nx=129`, `ny=100`, `nz=110`).\n",
                    "We use the default Lewis & Austin (2002) algorithm (`method=2`) and generate a corresponding field using the Seon (2012) algorithm (`method=1`) for comparison."
                ]
            })
        elif "fig, ax = plt.subplots" in source and "a.data" in source and "p.data" not in source and "c.data" not in source:
            new_cells.append({
                "cell_type": "markdown",
                "metadata": {},
                "source": [
                    "## 2. Visualization of the Density Field (Method 2)\n",
                    "\n",
                    "We visualize three orthogonal slices of the generated density field. Notice the rectangular shape of the grid bounds due to the non-cubic dimensions."
                ]
            })
        elif "fig, ax = plt.subplots" in source and "p.data" in source:
            new_cells.append({
                "cell_type": "markdown",
                "metadata": {},
                "source": [
                    "## 3. Visualization of the Density Field (Method 1)\n",
                    "\n",
                    "For comparison, we visualize the same orthogonal slices for the field generated using the Seon (2012) algorithm with the same random seed."
                ]
            })
        elif "kmin = 1.0" in source:
            new_cells.append({
                "cell_type": "markdown",
                "metadata": {},
                "source": [
                    "## 4. Generating Large-Scale Fluctuations Only\n",
                    "\n",
                    "By specifying `kmin` and `kmax`, we can limit the power spectrum to a specific range of wavenumbers. Here, we restrict the field to large-scale fluctuations (`kmin=1.0`, `kmax=3.0`)."
                ]
            })
        elif "calculate_PSD(a.data)" in source and "ynorm = calculate_PSD_norm" in source:
            new_cells.append({
                "cell_type": "markdown",
                "metadata": {},
                "source": [
                    "## 5. Power Spectrum Comparison\n",
                    "\n",
                    "We analyze and compare the power spectral densities (PSD) of the density fields generated by the three different setups:\n",
                    "- **Method 2** (blue)\n",
                    "- **Method 1** (orange)\n",
                    "- **Large-scale only** (green)"
                ]
            })
        elif "b = np.log(a.data)" in source:
            new_cells.append({
                "cell_type": "markdown",
                "metadata": {},
                "source": [
                    "## 6. Log-Density Power Spectrum Comparison\n",
                    "\n",
                    "We can also compare the power spectral densities of the logarithm of the density fields (`log(rho)`)."
                ]
            })
        elif "xmax = np.amax" in source:
            new_cells.append({
                "cell_type": "markdown",
                "metadata": {},
                "source": [
                    "## 7. Direct Density Comparison (Scatter Plot)\n",
                    "\n",
                    "A pixel-by-pixel scatter plot compares the density values generated by Method 1 versus Method 2. The red line represents a perfect 1-to-1 match."
                ]
            })
        elif "writeto" in source and "fits.gz" in source:
            new_cells.append({
                "cell_type": "markdown",
                "metadata": {},
                "source": [
                    "## 8. Exporting to FITS Format\n",
                    "\n",
                    "The generated density field can be easily saved as a FITS file for external analysis using the `.writeto()` method."
                ]
            })
        elif "centering = 'min'" in source:
            new_cells.append({
                "cell_type": "markdown",
                "metadata": {},
                "source": [
                    "## 9. Spatial Centering Options\n",
                    "\n",
                    "The `centering` option allows you to shift the periodic 3D field so that the minimum or maximum density pixel is located exactly at the center of the grid.\n",
                    "\n",
                    "### Minimum Density Centering\n",
                    "Using `centering='min'` places the lowest density region at the center of the field."
                ]
            })
        elif "centering = 'max'" in source:
            new_cells.append({
                "cell_type": "markdown",
                "metadata": {},
                "source": [
                    "### Maximum Density Centering\n",
                    "Using `centering='max'` places the highest density region at the center of the field."
                ]
            })
        new_cells.append(cell)
    else:
        new_cells.append(cell)

nb['cells'] = new_cells
with open('example2.ipynb', 'w') as f:
    json.dump(nb, f, indent=1)


# Process example3.ipynb
with open('example3.ipynb', 'r') as f:
    nb3 = json.load(f)

new_cells3 = []
for cell in nb3['cells']:
    if cell['cell_type'] == 'markdown' and 'fbm3d' in cell['source'][0]:
        new_cells3.append({
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "# fbm3d Example 3: Log-Normal Random Field Generation\n",
                "\n",
                "This notebook demonstrates how to:\n",
                "1. Use the `LogNormalRandomField` class directly instead of `fbm3d_ISM`\n",
                "2. Provide explicit log-normal distribution parameters (`sigma` and `slope`)\n",
                "3. Visualize the resulting density slices and analyze its power spectrum\n",
                "\n",
                "While `fbm3d_ISM` automatically calculates the appropriate `sigma` and `slope` based on interstellar medium parameters (Mach number and magnetic field), `LogNormalRandomField` gives you direct control over these underlying statistical properties."
            ]
        })
    elif cell['cell_type'] == 'code':
        source = "".join(cell['source'])
        if "nx = 256" in source:
            new_cells3.append({
                "cell_type": "markdown",
                "metadata": {},
                "source": [
                    "## 1. Generating the Log-Normal Field\n",
                    "\n",
                    "We specify `sigma=2.0` and `slope=3.0` directly to create a $256^3$ log-normal random field."
                ]
            })
        elif "fig, ax = plt.subplots" in source and "ln_data" in source:
            new_cells3.append({
                "cell_type": "markdown",
                "metadata": {},
                "source": [
                    "## 2. Visualization: 3D Density Slices\n",
                    "\n",
                    "Three orthogonal slices (xy, xz, yz) through the center of the 3D volume show the spatial structure of the generated field."
                ]
            })
        elif "kr_a, PSD_a = calculate_PSD" in source:
            new_cells3.append({
                "cell_type": "markdown",
                "metadata": {},
                "source": [
                    "## 3. Power Spectrum Analysis\n",
                    "\n",
                    "We analyze the power spectrum of the generated density field and compare it against the expected theoretical power-law line ($P(k) \\propto k^{-slope}$)."
                ]
            })
        elif "writeto" in source and "fits.gz" in source:
            new_cells3.append({
                "cell_type": "markdown",
                "metadata": {},
                "source": [
                    "## 4. Exporting to FITS Format\n",
                    "\n",
                    "Save the log-normal density field to a FITS file for further analysis."
                ]
            })
        new_cells3.append(cell)
    else:
        new_cells3.append(cell)

nb3['cells'] = new_cells3
with open('example3.ipynb', 'w') as f:
    json.dump(nb3, f, indent=1)
